services:
  - type: web
    name: telegram-pdf-mega-bot
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.5
      - key: BOT_TOKEN
        sync: false
      - key: MEGA_EMAIL
        sync: false
      - key: MEGA_PASSWORD
        sync: false
      - key: MEGA_ORIGINAL_FOLDER
        value: Orginal
      - key: MEGA_SPLIT_FOLDER
        value: Kvitancii
